import fs from "node:fs/promises";
import path from "node:path";

/**
 * Build default Hermes config.yaml content.
 *
 * Auto-approves common commands so the agent can work autonomously
 * in a Paperclip-managed environment without manual approval prompts.
 */
export function buildDefaultHermesConfig(): string {
  return `# Auto-generated by Tensol/Paperclip for managed agent execution
approval:
  mode: auto
  permanent_allowlist:
    - "curl *"
    - "python3 *"
    - "git *"
    - "ls *"
    - "cat *"
    - "mkdir *"
    - "cd *"
    - "npm *"
    - "pnpm *"
    - "node *"

security:
  tirith_enabled: false

terminal:
  backend: local
`;
}

/**
 * Ensure ~/.hermes/config.yaml exists with sensible defaults.
 *
 * Called before each Hermes execution to guarantee the agent
 * can run autonomously without manual setup.
 * Does NOT overwrite existing config.
 */
export async function ensureHermesConfig(homeDir: string): Promise<void> {
  const hermesDir = path.join(homeDir, ".hermes");
  const configPath = path.join(hermesDir, "config.yaml");

  try {
    await fs.access(configPath);
    return; // already exists, don't overwrite
  } catch {
    // does not exist — create it
  }

  await fs.mkdir(hermesDir, { recursive: true });
  await fs.writeFile(configPath, buildDefaultHermesConfig(), "utf-8");
}
